In [1]:
#QUESTION1
L=[]
for x in range(2000,3200):
    if (x%7==0) and (x%5==0):
        L.append(x)
print(L)


[2030, 2065, 2100, 2135, 2170, 2205, 2240, 2275, 2310, 2345, 2380, 2415, 2450, 2485, 2520, 2555, 2590, 2625, 2660, 2695, 2730, 2765, 2800, 2835, 2870, 2905, 2940, 2975, 3010, 3045, 3080, 3115, 3150, 3185]


In [2]:
#Question2
def factorial(n):
    if n<1:
        return 0
    elif (n==0) or (n==1):
        return 1
    else:
        f=1
        while (n>1):
            f=f*n 
            n=n-1
        return f

print('Factorial of',5,'is', factorial(5))

Factorial of 5 is 120


In [4]:
#Question3
def dict(n):
    d={}
    for i in range (1 , n+1):
        d[i]=i*i
        i+=1
    return d
         
print('Dict of the number', 8, 'is', dict(8))
        

Dict of the number 8 is {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [5]:
#Question4
def missing_char(ch, n):
    if n in range (0, (len(ch)-1)):
        str1 = lambda ch : ch[:n]
        str2 = lambda ch : ch[n+1:]
    return str1(ch)+str2(ch)
    
print(missing_char("kitten",1))
print(missing_char("kitten",0))
print(missing_char("kitten",4))

ktten
itten
kittn


In [6]:
#Question5
import numpy as np 
a= np.array([[0,1], [2,3], [4,5]])
a.tolist()

[[0, 1], [2, 3], [4, 5]]

In [7]:
#Question6
import numpy as np 
a=np.array([0, 1, 2])
print(a)
b=np.array([2, 1, 0])
print(b)
x=np.cov(a,b)
print(x)

[0 1 2]
[2 1 0]
[[ 1. -1.]
 [-1.  1.]]


In [11]:
#Question7
import math
C= 50
H = 30
D=[]
Dv=input("enter the value of D\n")
D=Dv.split(',')
D = [int(i) for i in D]
i=0
l = len(D)
output=[]
while(i<l):
    Q = round(math.sqrt((2*C*D[i])/H))
    output. append(Q)
    i+=1
print("output=",output)

enter the value of D
100,150,180
output= [18, 22, 24]
